### ISSUE TITLE
Errors in Hadoop HDFS TestFsDatasetCache test timed out

### ISSUE THREAD

**Issue by yussufsh** [OpenPOWER-BigData/HDP-Hadoop#2]
Results :

Tests in error:
  TestFsDatasetCache.testPageRounder:472 ?  test timed out after 60000 milliseco...
  TestFsDatasetCache.tearDown:149 ? Timeout Timed out waiting for condition. Thr...
  TestFsDatasetCache.testUncachingBlocksBeforeCachingFinishes:422 ? Timeout Time...
  TestFsDatasetCache.tearDown:149 ? Timeout Timed out waiting for condition. Thr...
  TestFsDatasetCache.testCacheAndUncacheBlockSimple:288->testCacheAndUncacheBlock:261 ? Timeout
  TestFsDatasetCache.tearDown:149 ? Timeout Timed out waiting for condition. Thr...
  TestFsDatasetCache.testFilesExceedMaxLockedMemory:346 ? Timeout Timed out wait...
  TestFsDatasetCache.tearDown:149 ? Timeout Timed out waiting for condition. Thr...
  TestFsDatasetCache.testCacheAndUncacheBlockWithRetries:315->testCacheAndUncacheBlock:261 ? Timeout
  TestFsDatasetCache.tearDown:149 ? Timeout Timed out waiting for condition. Thr...

Tests run: 13, Failures: 0, Errors: 10, Skipped: 0

**Comment by yussufsh** [comment]
After applying patch from below issues getting only error in testPageRounder.
https://issues.apache.org/jira/browse/HDFS-8520
https://issues.apache.org/jira/browse/HDFS-6515

Results :

Tests in error:
  TestFsDatasetCache.testPageRounder:472 ?  test timed out after 60000 milliseco...
  TestFsDatasetCache.tearDown:149 ? Timeout Timed out waiting for condition. Thr...

Tests run: 9, Failures: 0, Errors: 2, Skipped: 0

**Comment by yussufsh** [comment]
Could get only below exception trace, nothing in surefire report.

```
Running org.apache.hadoop.hdfs.server.datanode.TestFsDatasetCache
====> TEST TIMED OUT. PRINTING THREAD DUMP. <====
Timestamp: 2016-07-15 12:04:32,615
"IPC Server handler 4 on 40542" daemon prio=5 tid=39 timed_waiting
java.lang.Thread.State: TIMED_WAITING
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2082)
        at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
        at org.apache.hadoop.ipc.CallQueueManager.take(CallQueueManager.java:135)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2172)
"IPC Server handler 8 on 40542" daemon prio=5 tid=43 timed_waiting
java.lang.Thread.State: TIMED_WAITING
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2082)
        at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
        at org.apache.hadoop.ipc.CallQueueManager.take(CallQueueManager.java:135)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2172)
"IPC Server listener on 40542" daemon prio=5 tid=26 runnable
java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:102)
        at org.apache.hadoop.ipc.Server$Listener.run(Server.java:791)
"IPC Server idle connection scanner for port 40035" daemon prio=5 tid=81 timed_waiting
java.lang.Thread.State: TIMED_WAITING
        at java.lang.Object.wait(Native Method)
        at java.util.TimerThread.mainLoop(Timer.java:552)
        at java.util.TimerThread.run(Timer.java:505)
"Timer for 'NameNode' metrics system" daemon prio=5 tid=16 timed_waiting
java.lang.Thread.State: TIMED_WAITING
        at java.lang.Object.wait(Native Method)
        at java.util.TimerThread.mainLoop(Timer.java:552)
        at java.util.TimerThread.run(Timer.java:505)
"main"  prio=5 tid=1 runnable
java.lang.Thread.State: RUNNABLE
        at java.lang.Thread.dumpThreads(Native Method)
        at java.lang.Thread.getAllStackTraces(Thread.java:1640)
        at org.apache.hadoop.test.TimedOutTestsListener.buildThreadDump(TimedOutTestsListener.java:87)
        at org.apache.hadoop.test.TimedOutTestsListener.buildThreadDiagnosticString(TimedOutTestsListener.java:73)
        at org.apache.hadoop.test.TimedOutTestsListener.testFailure(TimedOutTestsListener.java:62)
        at org.junit.runner.notification.RunNotifier$4.notifyListener(RunNotifier.java:139)
        at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:61)
        at org.junit.runner.notification.RunNotifier.fireTestFailures(RunNotifier.java:134)
        at org.junit.runner.notification.RunNotifier.fireTestFailure(RunNotifier.java:128)
        at org.junit.internal.runners.model.EachTestNotifier.addFailure(EachTestNotifier.java:23)
        at org.junit.internal.runners.model.EachTestNotifier.addMultipleFailureException(EachTestNotifier.java:30)
        at org.junit.internal.runners.model.EachTestNotifier.addFailure(EachTestNotifier.java:21)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:275)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
"org.apache.hadoop.hdfs.server.namenode.FSNamesystem$LazyPersistFileScrubber@18ec9ac8" daemon prio=5 tid=50 timed_waiting
java.lang.Thread.State: TIMED_WAITING
        at java.lang.Thread.sleep(Native Method)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem$LazyPersistFileScrubber.run(FSNamesystem.java:4891)
        at java.lang.Thread.run(Thread.java:745)
"IPC Server handler 4 on 40035" daemon prio=5 tid=88 timed_waiting
java.lang.Thread.State: TIMED_WAITING
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:226)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2082)
        at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
        at org.apache.hadoop.ipc.CallQueueManager.take(CallQueueManager.java:135)
        at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2172)
"org.apache.hadoop.hdfs.server.namenode.LeaseManager$Monitor@18977673" daemon prio=5 tid=47 timed_waiting
java.lang.Thread.State: TIMED_WAITING
        at java.lang.Thread.sleep(Native Method)
        at org.apache.hadoop.hdfs.server.namenode.LeaseManager$Monitor.run(LeaseManager.java:429)
        at java.lang.Thread.run(Thread.java:745)
"IPC Server handler 1 on 40035" daemon prio=5 tid=85 timed_waiting`
```

**Comment by yussufsh** [comment]
Found related JIRA https://issues.apache.org/jira/browse/HDFS-8520 with patch file available. After applying the patch below 2 errors are still occurring.

TestFsDatasetCache.testPageRounder:472 ? test timed out after 60000 milliseco...
TestFsDatasetCache.tearDown:149 ? Timeout Timed out waiting for condition. Thr...
